package designpatterns.others;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import jakarta.annotation.PostConstruct;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

@SpringBootApplication
public class OrderManagementApplication {

    public static void main(String[] args) {
        SpringApplication.run(OrderManagementApplication.class, args);
    }
}

@RestController
@RequestMapping("/api/orders")
class OrderController {

    private final OrderApplicationService orderApplicationService;

    public OrderController(OrderApplicationService orderApplicationService) {
        this.orderApplicationService = orderApplicationService;
    }

    @PostMapping
    public ResponseEntity<OrderResponse> createOrder(@Valid @RequestBody CreateOrderRequest request) {
        OrderResponse response = orderApplicationService.createOrder(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }

    @GetMapping("/{orderId}")
    public ResponseEntity<OrderResponse> getOrderById(@PathVariable Long orderId) {
        return ResponseEntity.ok(orderApplicationService.getOrderById(orderId));
    }

    @GetMapping
    public ResponseEntity<List<OrderResponse>> getOrders(
            @RequestParam(name = "customerName", required = false) String customerName,
            @RequestParam(name = "status", required = false) OrderStatus status,
            @RequestParam(name = "sortBy", required = false) String sortBy,
            @RequestParam(name = "direction", required = false) String direction,
            @RequestParam(name = "page", defaultValue = "0") @Min(0) int page,
            @RequestParam(name = "size", defaultValue = "10") @Min(1) @Max(100) int size) {

        return ResponseEntity.ok(
                orderApplicationService.getOrders(customerName, status, sortBy, direction, page, size)
        );
    }

    @PutMapping("/{orderId}/status")
    public ResponseEntity<OrderResponse> updateStatus(
            @PathVariable Long orderId,
            @Valid @RequestBody UpdateOrderStatusRequest request) {
        return ResponseEntity.ok(orderApplicationService.updateStatus(orderId, request));
    }

    @PutMapping("/{orderId}")
    public ResponseEntity<OrderResponse> updateOrder(
            @PathVariable Long orderId,
            @Valid @RequestBody UpdateOrderRequest request) {
        return ResponseEntity.ok(orderApplicationService.updateOrder(orderId, request));
    }

    @DeleteMapping("/{orderId}")
    public ResponseEntity<Void> deleteOrder(@PathVariable Long orderId) {
        orderApplicationService.deleteOrder(orderId);
        return ResponseEntity.noContent().build();
    }

    @GetMapping("/summary")
    public ResponseEntity<OrderSummaryResponse> getSummary() {
        return ResponseEntity.ok(orderApplicationService.getSummary());
    }
}

@Service
class OrderApplicationService {

    // in-memory store for demonstration purposes. In real applications, this would be replaced by a database/repository layer.
    private final Map<Long, Order> store = new ConcurrentHashMap<>();
    // Simple ID generator for demo. In real applications, IDs would typically be generated by the database.
    private final AtomicLong idGenerator = new AtomicLong(1000L);

    @PostConstruct
    public void seedData() {
        createOrder(buildSeedRequest(
                "Pawan Mishra",
                "pawan@example.com",
                List.of(
                        new CreateOrderItemRequest("Laptop", 1, new BigDecimal("65000.00")),
                        new CreateOrderItemRequest("Mouse", 2, new BigDecimal("700.00"))
                ),
                "WELCOME10"
        ));

        createOrder(buildSeedRequest(
                "Rami Shukla",
                "rami@example.com",
                List.of(
                        new CreateOrderItemRequest("Keyboard", 1, new BigDecimal("2200.00")),
                        new CreateOrderItemRequest("Monitor", 2, new BigDecimal("12000.00"))
                ),
                null
        ));
    }

    private CreateOrderRequest buildSeedRequest(
            String customerName,
            String customerEmail,
            List<CreateOrderItemRequest> items,
            String couponCode
    ) {
        CreateOrderRequest request = new CreateOrderRequest();
        request.setCustomerName(customerName);
        request.setCustomerEmail(customerEmail);
        request.setItems(items);
        request.setCouponCode(couponCode);
        request.setPriority(false);
        return request;
    }

    public OrderResponse createOrder(CreateOrderRequest request) {
        validateItems(request.getItems());

        Long orderId = idGenerator.incrementAndGet();
        LocalDateTime now = LocalDateTime.now();

        List<OrderItem> orderItems = request.getItems()
                .stream()
                .map(this::toEntity)
                .collect(Collectors.toList());

        BigDecimal subTotal = calculateSubTotal(orderItems);
        BigDecimal discount = calculateDiscount(subTotal, request.getCouponCode(), request.isPriority());
        BigDecimal tax = calculateTax(subTotal.subtract(discount));
        BigDecimal finalAmount = subTotal.subtract(discount).add(tax);

        Order order = new Order();
        order.setId(orderId);
        order.setCustomerName(request.getCustomerName());
        order.setCustomerEmail(request.getCustomerEmail());
        order.setItems(orderItems);
        order.setCouponCode(request.getCouponCode());
        order.setPriority(request.isPriority());
        order.setSubTotal(subTotal);
        order.setDiscount(discount);
        order.setTax(tax);
        order.setFinalAmount(finalAmount);
        order.setStatus(OrderStatus.CREATED);
        order.setCreatedAt(now);
        order.setUpdatedAt(now);
        order.setNotes(request.getNotes());

        store.put(orderId, order);
        return toResponse(order);
    }

    public OrderResponse getOrderById(Long orderId) {
        Order order = store.get(orderId);
        if (order == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Order not found with id: " + orderId);
        }
        return toResponse(order);
    }

    public List<OrderResponse> getOrders(
            String customerName,
            OrderStatus status,
            String sortBy,
            String direction,
            int page,
            int size
    ) {
        Comparator<Order> comparator = resolveComparator(sortBy, direction);

        List<Order> filtered = store.values()
                .stream()
                .filter(order -> customerName == null || order.getCustomerName().toLowerCase().contains(customerName.toLowerCase()))
                .filter(order -> status == null || order.getStatus() == status)
                .sorted(comparator)
                .collect(Collectors.toList());

        int start = page * size;
        int end = Math.min(start + size, filtered.size());

        if (start > filtered.size()) {
            return Collections.emptyList();
        }

        return filtered.subList(start, end)
                .stream()
                .map(this::toResponse)
                .collect(Collectors.toList());
    }

    public OrderResponse updateStatus(Long orderId, UpdateOrderStatusRequest request) {
        Order order = fetchOrder(orderId);

        if (order.getStatus() == OrderStatus.CANCELLED) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Cancelled order cannot be updated");
        }

        if (request.getStatus() == OrderStatus.DELIVERED && order.getItems().isEmpty()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Empty order cannot be delivered");
        }

        order.setStatus(request.getStatus());
        order.setUpdatedAt(LocalDateTime.now());

        return toResponse(order);
    }

    public OrderResponse updateOrder(Long orderId, UpdateOrderRequest request) {
        Order existing = fetchOrder(orderId);

        if (existing.getStatus() == OrderStatus.DELIVERED) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Delivered order cannot be modified");
        }

        if (request.getCustomerName() != null && !request.getCustomerName().isBlank()) {
            existing.setCustomerName(request.getCustomerName());
        }

        if (request.getCustomerEmail() != null && !request.getCustomerEmail().isBlank()) {
            existing.setCustomerEmail(request.getCustomerEmail());
        }

        if (request.getNotes() != null) {
            existing.setNotes(request.getNotes());
        }

        if (request.getPriority() != null) {
            existing.setPriority(request.getPriority());
        }

        if (request.getCouponCode() != null) {
            existing.setCouponCode(request.getCouponCode());
        }

        if (request.getItems() != null && !request.getItems().isEmpty()) {
            validateItems(request.getItems());

            List<OrderItem> updatedItems = request.getItems()
                    .stream()
                    .map(this::toEntity)
                    .collect(Collectors.toList());

            existing.setItems(updatedItems);

            BigDecimal subTotal = calculateSubTotal(updatedItems);
            BigDecimal discount = calculateDiscount(subTotal, existing.getCouponCode(), existing.isPriority());
            BigDecimal tax = calculateTax(subTotal.subtract(discount));
            BigDecimal finalAmount = subTotal.subtract(discount).add(tax);

            existing.setSubTotal(subTotal);
            existing.setDiscount(discount);
            existing.setTax(tax);
            existing.setFinalAmount(finalAmount);
        }

        existing.setUpdatedAt(LocalDateTime.now());

        return toResponse(existing);
    }

    public void deleteOrder(Long orderId) {
        Order existing = store.get(orderId);
        if (existing == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Order not found with id: " + orderId);
        }

        if (existing.getStatus() == OrderStatus.SHIPPED || existing.getStatus() == OrderStatus.DELIVERED) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Shipped or delivered order cannot be deleted");
        }

        store.remove(orderId);
    }

    public OrderSummaryResponse getSummary() {
        List<Order> allOrders = new ArrayList<>(store.values());

        long totalOrders = allOrders.size();
        long createdOrders = allOrders.stream().filter(o -> o.getStatus() == OrderStatus.CREATED).count();
        long confirmedOrders = allOrders.stream().filter(o -> o.getStatus() == OrderStatus.CONFIRMED).count();
        long shippedOrders = allOrders.stream().filter(o -> o.getStatus() == OrderStatus.SHIPPED).count();
        long deliveredOrders = allOrders.stream().filter(o -> o.getStatus() == OrderStatus.DELIVERED).count();
        long cancelledOrders = allOrders.stream().filter(o -> o.getStatus() == OrderStatus.CANCELLED).count();

        BigDecimal totalRevenue = allOrders.stream()
                .map(Order::getFinalAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        BigDecimal averageOrderValue = totalOrders == 0
                ? BigDecimal.ZERO
                : totalRevenue.divide(BigDecimal.valueOf(totalOrders), 2, RoundingMode.HALF_UP);

        OrderSummaryResponse summary = new OrderSummaryResponse();
        summary.setTotalOrders(totalOrders);
        summary.setCreatedOrders(createdOrders);
        summary.setConfirmedOrders(confirmedOrders);
        summary.setShippedOrders(shippedOrders);
        summary.setDeliveredOrders(deliveredOrders);
        summary.setCancelledOrders(cancelledOrders);
        summary.setTotalRevenue(totalRevenue);
        summary.setAverageOrderValue(averageOrderValue);

        return summary;
    }

    private Order fetchOrder(Long orderId) {
        Order order = store.get(orderId);
        if (order == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Order not found with id: " + orderId);
        }
        return order;
    }

    private void validateItems(List<? extends BaseItemRequest> items) {
        if (items == null || items.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Order must contain at least one item");
        }

        for (BaseItemRequest item : items) {
            if (item.getProductName() == null || item.getProductName().isBlank()) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Product name cannot be blank");
            }
            if (item.getQuantity() == null || item.getQuantity() <= 0) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Quantity must be greater than zero");
            }
            if (item.getUnitPrice() == null || item.getUnitPrice().compareTo(BigDecimal.ZERO) < 0) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Unit price cannot be negative");
            }
        }
    }

    private OrderItem toEntity(BaseItemRequest request) {
        OrderItem item = new OrderItem();
        item.setProductName(request.getProductName());
        item.setQuantity(request.getQuantity());
        item.setUnitPrice(request.getUnitPrice());
        item.setLineAmount(request.getUnitPrice().multiply(BigDecimal.valueOf(request.getQuantity())));
        return item;
    }

    private BigDecimal calculateSubTotal(List<OrderItem> items) {
        return items.stream()
                .map(OrderItem::getLineAmount)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    private BigDecimal calculateDiscount(BigDecimal subTotal, String couponCode, boolean priority) {
        BigDecimal discount = BigDecimal.ZERO;

        if (couponCode != null && !couponCode.isBlank()) {
            if ("WELCOME10".equalsIgnoreCase(couponCode)) {
                discount = discount.add(subTotal.multiply(new BigDecimal("0.10")));
            } else if ("FLAT500".equalsIgnoreCase(couponCode) && subTotal.compareTo(new BigDecimal("5000")) > 0) {
                discount = discount.add(new BigDecimal("500"));
            } else if ("SUPER20".equalsIgnoreCase(couponCode) && subTotal.compareTo(new BigDecimal("10000")) >= 0) {
                discount = discount.add(subTotal.multiply(new BigDecimal("0.20")));
            }
        }

        if (priority) {
            discount = discount.add(new BigDecimal("100"));
        }

        return discount.setScale(2, RoundingMode.HALF_UP);
    }

    private BigDecimal calculateTax(BigDecimal taxableAmount) {
        return taxableAmount.multiply(new BigDecimal("0.18"))
                .setScale(2, RoundingMode.HALF_UP);
    }

    private Comparator<Order> resolveComparator(String sortBy, String direction) {
        Comparator<Order> comparator;

        if ("customerName".equalsIgnoreCase(sortBy)) {
            comparator = Comparator.comparing(Order::getCustomerName, String.CASE_INSENSITIVE_ORDER);
        } else if ("finalAmount".equalsIgnoreCase(sortBy)) {
            comparator = Comparator.comparing(Order::getFinalAmount);
        } else if ("status".equalsIgnoreCase(sortBy)) {
            comparator = Comparator.comparing(Order::getStatus);
        } else {
            comparator = Comparator.comparing(Order::getCreatedAt);
        }

        if ("desc".equalsIgnoreCase(direction)) {
            comparator = comparator.reversed();
        }

        return comparator;
    }

    private OrderResponse toResponse(Order order) {
        List<OrderItemResponse> itemResponses = order.getItems()
                .stream()
                .map(item -> {
                    OrderItemResponse response = new OrderItemResponse();
                    response.setProductName(item.getProductName());
                    response.setQuantity(item.getQuantity());
                    response.setUnitPrice(item.getUnitPrice());
                    response.setLineAmount(item.getLineAmount());
                    return response;
                })
                .collect(Collectors.toList());

        OrderResponse response = new OrderResponse();
        response.setId(order.getId());
        response.setCustomerName(order.getCustomerName());
        response.setCustomerEmail(order.getCustomerEmail());
        response.setItems(itemResponses);
        response.setCouponCode(order.getCouponCode());
        response.setPriority(order.isPriority());
        response.setSubTotal(order.getSubTotal());
        response.setDiscount(order.getDiscount());
        response.setTax(order.getTax());
        response.setFinalAmount(order.getFinalAmount());
        response.setStatus(order.getStatus());
        response.setCreatedAt(order.getCreatedAt());
        response.setUpdatedAt(order.getUpdatedAt());
        response.setNotes(order.getNotes());
        return response;
    }
}

enum OrderStatus {
    CREATED,
    CONFIRMED,
    SHIPPED,
    DELIVERED,
    CANCELLED
}

class Order {
    private Long id;
    private String customerName;
    private String customerEmail;
    private List<OrderItem> items = new ArrayList<>();
    private String couponCode;
    private boolean priority;
    private BigDecimal subTotal;
    private BigDecimal discount;
    private BigDecimal tax;
    private BigDecimal finalAmount;
    private OrderStatus status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private String notes;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    public void setItems(List<OrderItem> items) {
        this.items = items;
    }

    public String getCouponCode() {
        return couponCode;
    }

    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    public boolean isPriority() {
        return priority;
    }

    public void setPriority(boolean priority) {
        this.priority = priority;
    }

    public BigDecimal getSubTotal() {
        return subTotal;
    }

    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }

    public BigDecimal getDiscount() {
        return discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    public BigDecimal getTax() {
        return tax;
    }

    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    public BigDecimal getFinalAmount() {
        return finalAmount;
    }

    public void setFinalAmount(BigDecimal finalAmount) {
        this.finalAmount = finalAmount;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createAt) {
        this.createdAt = createAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updateAt) {
        this.updatedAt = updateAt;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }
}

class OrderItem {
    private String productName;
    private Integer quantity;
    private BigDecimal unitPrice;
    private BigDecimal lineAmount;

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public BigDecimal getLineAmount() {
        return lineAmount;
    }

    public void setLineAmount(BigDecimal lineAmount) {
        this.lineAmount = lineAmount;
    }
}

abstract class BaseItemRequest {
    @NotBlank
    private String productName;

    @NotNull
    @Min(1)
    private Integer quantity;

    @NotNull
    private BigDecimal unitPrice;

    public BaseItemRequest() {
    }

    public BaseItemRequest(String productName, Integer quantity, BigDecimal unitPrice) {
        this.productName = productName;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
}

class CreateOrderItemRequest extends BaseItemRequest {
    public CreateOrderItemRequest() {
    }

    public CreateOrderItemRequest(String productName, Integer quantity, BigDecimal unitPrice) {
        super(productName, quantity, unitPrice);
    }
}

class UpdateOrderItemRequest extends BaseItemRequest {
    public UpdateOrderItemRequest() {
    }

    public UpdateOrderItemRequest(String productName, Integer quantity, BigDecimal unitPrice) {
        super(productName, quantity, unitPrice);
    }
}

class CreateOrderRequest {
    @NotBlank
    private String customerName;

    @NotBlank
    private String customerEmail;

    @NotNull
    @Valid
    private List<CreateOrderItemRequest> items;

    private String couponCode;
    private boolean priority;
    private String notes;

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    public List<CreateOrderItemRequest> getItems() {
        return items;
    }

    public void setItems(List<CreateOrderItemRequest> items) {
        this.items = items;
    }

    public String getCouponCode() {
        return couponCode;
    }

    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    public boolean isPriority() {
        return priority;
    }

    public void setPriority(boolean priority) {
        this.priority = priority;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }
}

class UpdateOrderRequest {
    private String customerName;
    private String customerEmail;

    @Valid
    private List<UpdateOrderItemRequest> items;

    private String couponCode;
    private Boolean priority;
    private String notes;

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    public List<UpdateOrderItemRequest> getItems() {
        return items;
    }

    public void setItems(List<UpdateOrderItemRequest> items) {
        this.items = items;
    }

    public String getCouponCode() {
        return couponCode;
    }

    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    public Boolean getPriority() {
        return priority;
    }

    public void setPriority(Boolean priority) {
        this.priority = priority;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }
}

class UpdateOrderStatusRequest {
    @NotNull
    private OrderStatus status;

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }
}

class OrderItemResponse {
    private String productName;
    private Integer quantity;
    private BigDecimal unitPrice;
    private BigDecimal lineAmount;

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public BigDecimal getLineAmount() {
        return lineAmount;
    }

    public void setLineAmount(BigDecimal lineAmount) {
        this.lineAmount = lineAmount;
    }
}

class OrderResponse {
    private Long id;
    private String customerName;
    private String customerEmail;
    private List<OrderItemResponse> items;
    private String couponCode;
    private boolean priority;
    private BigDecimal subTotal;
    private BigDecimal discount;
    private BigDecimal tax;
    private BigDecimal finalAmount;
    private OrderStatus status;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private String notes;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    public List<OrderItemResponse> getItems() {
        return items;
    }

    public void setItems(List<OrderItemResponse> items) {
        this.items = items;
    }

    public String getCouponCode() {
        return couponCode;
    }

    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    public boolean isPriority() {
        return priority;
    }

    public void setPriority(boolean priority) {
        this.priority = priority;
    }

    public BigDecimal getSubTotal() {
        return subTotal;
    }

    public void setSubTotal(BigDecimal subTotal) {
        this.subTotal = subTotal;
    }

    public BigDecimal getDiscount() {
        return discount;
    }

    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    public BigDecimal getTax() {
        return tax;
    }

    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    public BigDecimal getFinalAmount() {
        return finalAmount;
    }

    public void setFinalAmount(BigDecimal finalAmount) {
        this.finalAmount = finalAmount;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }
}

class OrderSummaryResponse {
    private long totalOrders;
    private long createdOrders;
    private long confirmedOrders;
    private long shippedOrders;
    private long deliveredOrders;
    private long cancelledOrders;
    private BigDecimal totalRevenue;
    private BigDecimal averageOrderValue;

    public long getTotalOrders() {
        return totalOrders;
    }

    public void setTotalOrders(long totalOrders) {
        this.totalOrders = totalOrders;
    }

    public long getCreatedOrders() {
        return createdOrders;
    }

    public void setCreatedOrders(long createdOrders) {
        this.createdOrders = createdOrders;
    }

    public long getConfirmedOrders() {
        return confirmedOrders;
    }

    public void setConfirmedOrders(long confirmedOrders) {
        this.confirmedOrders = confirmedOrders;
    }

    public long getShippedOrders() {
        return shippedOrders;
    }

    public void setShippedOrders(long shippedOrders) {
        this.shippedOrders = shippedOrders;
    }

    public long getDeliveredOrders() {
        return deliveredOrders;
    }

    public void setDeliveredOrders(long deliveredOrders) {
        this.deliveredOrders = deliveredOrders;
    }

    public long getCancelledOrders() {
        return cancelledOrders;
    }

    public void setCancelledOrders(long cancelledOrders) {
        this.cancelledOrders = cancelledOrders;
    }

    public BigDecimal getTotalRevenue() {
        return totalRevenue;
    }

    public void setTotalRevenue(BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }

    public BigDecimal getAverageOrderValue() {
        return averageOrderValue;
    }

    public void setAverageOrderValue(BigDecimal averageOrderValue) {
        this.averageOrderValue = averageOrderValue;
    }
}